default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("PGUSER") %>
  password: <%= ENV.fetch("PGPASSWORD") %>
  host: <%= ENV.fetch("PGHOST") %>
  database: <%= ENV.fetch("POSTGRES_DB") %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
